MultiAuthDemo/Areas/AdminsArea/Controllers/VehicleController.cs
using ASC.Common;
using ASC.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MultiAuthDemo.Areas.AdminsArea.Controllers
{
    public class VehicleController : Controller
    {
        // GET: AdminsArea/Vehicle
        public ActionResult Index()
        {
            IEnumerable<Vehicle> vehicles;

            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri("https://localhost:44318/Vehicle/");
                //HTTP GET
                var responseTask = client.GetAsync("Get");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IEnumerable<Vehicle>>();
                    readTask.Wait();
                    vehicles = readTask.Result;
                }
                else
                {
                    vehicles = Enumerable.Empty<Vehicle>();
                    ModelState.AddModelError(string.Empty, "Server error occured while retriving data");
                }
            }

            return View(vehicles);
        }

        // GET: AdminsArea/Vehicle/Create
        public ActionResult Create()
        {
            IEnumerable<Model> models;
            IEnumerable<Customer> customers;
            Vehicle vehicle = new Vehicle();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44318/");
                //HTTP GET
                var responseTask = client.GetAsync("Model/Get");
                var responseTask2 = client.GetAsync("Customer/Get/");
                responseTask.Wait();
                responseTask2.Wait();
                var result = responseTask.Result;
                var result2 = responseTask2.Result;
                if (result.IsSuccessStatusCode && result2.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IEnumerable<Model>>();
                    readTask.Wait();
                    models = readTask.Result;

                    var readTask2 = result2.Content.ReadAsAsync <IEnumerable<Customer>>();
                    readTask2.Wait();
                    customers = readTask2.Result;
                }
                else
                {
                    models = Enumerable.Empty<Model>();
                    customers = Enumerable.Empty<Customer>();
                    vehicle = null;
                    ModelState.AddModelError(string.Empty, "Server error occured while retriving data");
                }
            }
            VehicleFormModel entity = new VehicleFormModel
            {
                models = models,
                customers = customers,
                vehicle = vehicle
            };

            return PartialView(entity);
        }

        // POST: AdminsArea/Brand/Create
        [HttpPost]
        public ActionResult Create(Vehicle vehicle)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:44318/Vehicle/");

                    //HTTP POST
                    var postTask = client.PostAsJsonAsync<Vehicle>("Create", vehicle);
                    postTask.Wait();

                    var result = postTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        TempData["Type"] = 0;
                        TempData["Message"] = "Model Added successfully";
                        return RedirectToAction("Index");
                    }
                }
                TempData["Type"] = 2;
                TempData["Message"] = "Error Occured While Creating";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminsArea/Vehicle/Edit/5
        public ActionResult Edit(int id)
        {
            IEnumerable<Model> models;
            IEnumerable<Customer> customers;
            Vehicle vehicle = new Vehicle();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44318/");
                //HTTP GET
                var responseTask = client.GetAsync("Model/Get");
                var responseTask2 = client.GetAsync("Customer/Get/");
                var responseTask3 = client.GetAsync("Vehicle/Get/" + id);
                responseTask.Wait();
                responseTask2.Wait();
                responseTask3.Wait();
                var result = responseTask.Result;
                var result2 = responseTask2.Result;
                var result3 = responseTask3.Result;
                if (result.IsSuccessStatusCode && result2.IsSuccessStatusCode && result3.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IEnumerable<Model>>();
                    readTask.Wait();
                    models = readTask.Result;

                    var readTask2 = result2.Content.ReadAsAsync<IEnumerable<Customer>>();
                    readTask2.Wait();
                    customers = readTask2.Result;

                    var readTask3 = result3.Content.ReadAsAsync<Vehicle>();
                    readTask3.Wait();
                    vehicle = readTask3.Result;
                }
                else
                {
                    models = Enumerable.Empty<Model>();
                    customers = Enumerable.Empty<Customer>();
                    vehicle = null;
                    ModelState.AddModelError(string.Empty, "Server error occured while retriving data");
                }
            }
            VehicleFormModel entity = new VehicleFormModel
            {
                models = models,
                customers = customers,
                vehicle = vehicle
            };

            return PartialView(entity);
        }

        // POST: AdminsArea/Vehicle/Edit/5
        [HttpPost]
        public ActionResult Edit(Vehicle vehicle)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:44318/Vehicle/");

                    //HTTP PUT
                    var putTask = client.PutAsJsonAsync<Vehicle>("Edit", vehicle);
                    putTask.Wait();

                    var result = putTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        TempData["Type"] = 1;
                        TempData["Message"] = "Model Edited successfully";
                        return RedirectToAction("Index");
                    }
                }
                TempData["Type"] = 2;
                TempData["Message"] = "Error Occured While Updating";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminsArea/Vehicle/Delete/5
        public ActionResult Delete(int id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44318/Vehicle/");

                //HTTP DELETE
                var deleteTask = client.DeleteAsync("Delete/" + id);
                deleteTask.Wait();

                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    TempData["Type"] = 1;
                    TempData["Message"] = "Model Status Changed successfully";
                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Index");
        }
    }
}

MultiAuthDemo/Areas/DealersArea/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MultiAuthDemo.Areas.DealersArea.Controllers
{
    public class VehicleController : Controller
    {
        // GET: DealersArea/Vehicle
        public ActionResult Index()
        {
            return View();
        }

        // GET: DealersArea/Vehicle/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DealersArea/Vehicle/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DealersArea/Vehicle/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: DealersArea/Vehicle/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DealersArea/Vehicle/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: DealersArea/Vehicle/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DealersArea/Vehicle/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MultiAuthDemo/Areas/AdminsArea/Views/Vehicle/Create.cshtml
@model ASC.Common.VehicleFormModel

@{
    ViewBag.Title = "Create";
}


<div class="modal-content">
    <div class="form-horizontal">
        @using (Html.BeginForm("Create", "Vehicle", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="card-body">
            <h5 class="card-title">
                Vehicle Form
                <span class="close" id="close">&times;</span>
            </h5>
            <br>
            <div class="form-group row">
                @Html.LabelFor(model => model.vehicle.Name, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.vehicle.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.vehicle.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.vehicle.NumberPlate, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.vehicle.NumberPlate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.vehicle.NumberPlate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.vehicle.ChassisNumber, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.vehicle.ChassisNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.vehicle.ChassisNumber, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.vehicle.RegistrationDate, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.vehicle.RegistrationDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.vehicle.RegistrationDate, "", new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.vehicle.LastServiceDate, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.vehicle.LastServiceDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.vehicle.LastServiceDate, "", new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.vehicle.FuelType, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.vehicle.FuelType, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.vehicle.FuelType, "", new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.vehicle.CustomerId, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.vehicle.CustomerId, new SelectList(Model.customers, "Id", "Name"), "Select", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.vehicle.CustomerId, "", new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.vehicle.ModelId, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.vehicle.ModelId, new SelectList(Model.models, "Id", "Name"), "Select", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.vehicle.ModelId, "", new { @class = "text-danger" })
                </div>

            </div>
        </div>

            <div class="border-top">
                <div class="card-body" align="center">
                    <button type="Submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        }
    </div>
</div>

MultiAuthDemo/Areas/AdminsArea/Views/Vehicle/Edit.cshtml
@model ASC.Common.VehicleFormModel

@{
    ViewBag.Title = "Edit";
}

<div class="modal-content">
    <div class="form-horizontal">
        @using (Html.BeginForm("Edit", "Vehicle", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.vehicle.Id)
            <div class="card-body">
                <h5 class="card-title">
                    Edit Vehicle
                    <span class="close" id="close">&times;</span>
                </h5>
                <br>
                <div class="form-group row">
                    @Html.LabelFor(model => model.vehicle.Name, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.vehicle.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.vehicle.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.vehicle.NumberPlate, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.vehicle.NumberPlate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.vehicle.NumberPlate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.vehicle.ChassisNumber, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.vehicle.ChassisNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.vehicle.ChassisNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.vehicle.RegistrationDate, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.vehicle.RegistrationDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.vehicle.RegistrationDate, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.vehicle.LastServiceDate, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.vehicle.LastServiceDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.vehicle.LastServiceDate, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.vehicle.FuelType, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.vehicle.FuelType, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.vehicle.FuelType, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.vehicle.CustomerId, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.vehicle.CustomerId, new SelectList(Model.customers, "Id", "Name"), "Select", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.vehicle.CustomerId, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.vehicle.ModelId, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.vehicle.ModelId, new SelectList(Model.models, "Id", "Name"), "Select", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.vehicle.ModelId, "", new { @class = "text-danger" })
                    </div>

                </div>
            </div>

            <div class="border-top">
                <div class="card-body" align="center">
                    <button type="Submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        }
    </div>
</div>

MultiAuthDemo/Areas/AdminsArea/Views/Vehicle/Index.cshtml
@model IEnumerable<ASC.Entities.Vehicle>

@{
    ViewBag.Title = "Index";
}
<link href="~/Template/css/Popup-form.css" rel="stylesheet" />

<div class="container-fluid">
    <h1 class="mt-4">Vehicles</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">
            <button id="myBtn" type="Submit" class="btn btn-danger" style="float: right;"><i class="fas fa-plus"></i> Vehicle</button>
        </li>
    </ol>

    <div class="card mb-4">
        <div class="card-header">

            <i class="fas fa-table mr-1"></i>
            DataTable Example
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.NumberPlate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ChassisNumber)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RegistrationDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LastServiceDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FuelType)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Customer.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Model.Name)
                            </th>
                            <th>

                            </th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NumberPlate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ChassisNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.RegistrationDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LastServiceDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FuelType)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Customer.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Model.Name)
                            </td>
                            <td>
                                <button type="Submit" value="@item.Id" class="Editform btn btn-primary">
                                    <i class="far fa-edit"></i>
                                </button>
                                    <a href='@Url.Action("Delete","Vehicle", new { id = item.Id })' class="btn btn-danger">
                                        <i class="fas fa-toggle-off"></i>
                                    </a>
                                
                            </td>
                        </tr>
                        }
                    </tbody>

                    <tfoot>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.NumberPlate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ChassisNumber)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RegistrationDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LastServiceDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FuelType)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Customer.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Model.Name)
                            </th>
                            <th>

                            </th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>


</div>

<div id="myModal" class="modal" style="width:100%; padding-right:30%;">

</div>


@section scripts{
    <script>
        $(document).ready(function () {
            $("#myBtn").click(function (evt) {

                $.get( '@Url.Action("Create", "Vehicle", new {} )', function(data) {
                    $('#myModal').html(data);
                    $('#myModal').css("display", "block");
                });
            });

            $(".Editform").click(function (evt) {
                var CatID = $(this).val();
                $.get('@Url.Action("Edit", "Vehicle")?id=' + CatID, function(data) {
                    $('#myModal').html(data);
                    $('#myModal').css("display","block");
                });
            });
        });
    </script>

    <script type="text/javascript">
        var modal = document.getElementById("myModal");
        window.onclick = function (event) {
            if (event.target == modal) {
                modal.style.display = "none";
                modal.innerHTML = "";
            }
        }
    </script>



    <script>
    $(document).ready(function () {
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "onclick": null,
            "showDuration": "200",
            "hideDuration": "1500",
            "timeOut": "6000",
            "extendedTimeOut": "1200",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        };

        var Type = "@TempData["Type"]";
        var Message = "@TempData["Message"]";
        if (Type == "0") {
            toastr.success(Message, 'The Site Says')
        } else if (Type == "1") {
            toastr.info(Message, 'The Site Says')
        } else if (Type == "2") {
            toastr.warning(Message, 'The Site Says')
        } else if (Type == "3") {
            toastr.error(Message, 'Inconceivable!')
        }
    });
    </script>
}