MultiAuthDemo/Models/AccountViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MultiAuthDemo.Models
{
    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class ExternalLoginListViewModel
    {
        public string ReturnUrl { get; set; }
    }

    public class SendCodeViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
        public string ReturnUrl { get; set; }
        public bool RememberMe { get; set; }
    }

    public class VerifyCodeViewModel
    {
        [Required]
        public string Provider { get; set; }

        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }
        public string ReturnUrl { get; set; }

        [Display(Name = "Remember this browser?")]
        public bool RememberBrowser { get; set; }

        public bool RememberMe { get; set; }
    }

    public class ForgotViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "UserName")]

        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "UserRoles")]
        public string UserRoles { get; set; }
        
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "UserName")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        public string Code { get; set; }
    }

    public class ForgotPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

MultiAuthDemo/Models/IdentityModels.cs
using System.Data.Entity;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace MultiAuthDemo.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit https://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    public class ApplicationUser : IdentityUser
    {
        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ApplicationUser> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;
        }
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext()
            : base("DefaultConnection", throwIfV1Schema: false)
        {
        }

        public static ApplicationDbContext Create()
        {
            return new ApplicationDbContext();
        }
    }
}

MultiAuthDemo/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace MultiAuthDemo.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

MultiAuthDemo/Areas/AdminsArea/Controllers/ModelController.cs
using ASC.Common;
using ASC.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MultiAuthDemo.Areas.AdminsArea.Controllers
{
    public class ModelController : Controller
    {
        public ActionResult Index()
        {
            IEnumerable<Model> models;

            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri("https://localhost:44318/Model/");
                //HTTP GET
                var responseTask = client.GetAsync("Get");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IEnumerable<Model>>();
                    readTask.Wait();
                    models = readTask.Result;
                }
                else
                {
                    models = Enumerable.Empty<Model>();
                    ModelState.AddModelError(string.Empty, "Server error occured while retriving data");
                }
            }

            return View(models);
        }

        // GET: AdminsArea/Brand/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AdminsArea/Brand/Create
        public ActionResult Create()
        {
            IEnumerable<Brand> brands;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44318/Brand/");
                //HTTP GET
                var responseTask = client.GetAsync("Get");
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IEnumerable<Brand>>();
                    readTask.Wait();
                    brands = readTask.Result;
                }
                else
                {
                    brands = Enumerable.Empty<Brand>();
                }
            }
            ModelFormViewModel entity = new ModelFormViewModel
            {
                brands = brands,
                modelData = new Model()
            };
            
            return PartialView(entity);
        }

        // POST: AdminsArea/Brand/Create
        [HttpPost]
        public ActionResult Create(Model modelData)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:44318/Model/");

                    //HTTP POST
                    var postTask = client.PostAsJsonAsync<Model>("Create", modelData);
                    postTask.Wait();
                    /*var post = client.PostAsJsonAsync<Vehicle>("Vehicle/Create", vehicle).Result;*/

                    var result = postTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        TempData["Type"] = 0;
                        TempData["Message"] = "Model Added successfully";
                        return RedirectToAction("Index");
                    }
                }
                TempData["Type"] = 2;
                TempData["Message"] = "Error Occured While Creating";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminsArea/Brand/Edit/5
        public ActionResult Edit(int id)
        {
            IEnumerable<Brand> brands;
            Model model = new Model();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44318/");
                //HTTP GET
                var responseTask = client.GetAsync("Brand/Get");
                var responseTask2 = client.GetAsync("Model/Get/" + id);
                responseTask.Wait();
                responseTask2.Wait();
                var result = responseTask.Result;
                var result2 = responseTask2.Result;
                if (result.IsSuccessStatusCode && result2.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IEnumerable<Brand>>();
                    readTask.Wait();
                    brands = readTask.Result;

                    var readTask2 = result2.Content.ReadAsAsync<Model>();
                    readTask2.Wait();
                    model = readTask2.Result;
                }
                else
                {
                    brands = Enumerable.Empty<Brand>();
                    model = null;
                    ModelState.AddModelError(string.Empty, "Server error occured while retriving data");
                }
            }
            ModelFormViewModel entity = new ModelFormViewModel
            {
                brands = brands,
                modelData = model
            };

            return PartialView(entity);
            
        }

        // POST: AdminsArea/Brand/Edit/5
        [HttpPost]
        public ActionResult Edit(Model modelData)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:44318/Model/");

                    //HTTP PUT
                    var putTask = client.PutAsJsonAsync<Model>("Edit", modelData);
                    putTask.Wait();

                    var result = putTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        TempData["Type"] = 1;
                        TempData["Message"] = "Model Edited successfully";
                        return RedirectToAction("Index");
                    }
                }
                TempData["Type"] = 2;
                TempData["Message"] = "Error Occured While Updating";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminsArea/Brand/Delete/5
        public ActionResult Delete(int id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44318/Model/");

                //HTTP DELETE
                var deleteTask = client.DeleteAsync("Delete/" + id);
                deleteTask.Wait();

                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    TempData["Type"] = 1;
                    TempData["Message"] = "Model Status Changed successfully";
                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Index");
        }

        // POST: AdminsArea/Brand/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MultiAuthDemo/Areas/AdminsArea/Views/Model/Create.cshtml
@model ASC.Common.ModelFormViewModel

<div class="modal-content">
    <div class="form-horizontal">
        @using (Html.BeginForm("Create", "Model", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

        <div class="card-body">
            <h5 class="card-title">
                Model Form
                <span class="close" id="close">&times;</span>
            </h5>
            <br>
            <div class="form-group row">
                @Html.LabelFor(model => model.modelData.Name, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.modelData.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.modelData.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.modelData.BrandId, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.modelData.BrandId, new SelectList(Model.brands, "Id", "Name"), "Select", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.modelData.BrandId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.modelData.IsActive, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })

                <div class="col-md-9">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.modelData.IsActive)
                        @Html.ValidationMessageFor(model => model.modelData.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

            <div class="border-top">
                <div class="card-body" align="center">
                    <button type="Submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        }
    </div>
</div>

MultiAuthDemo/Areas/AdminsArea/Views/Model/Edit.cshtml
@model ASC.Common.ModelFormViewModel

<div class="modal-content">
    <div class="form-horizontal">
        @using (Html.BeginForm("Edit", "Model", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

        <div class="card-body">
            <h5 class="card-title">
                Edit Model
                <span class="close" id="close">&times;</span>
            </h5>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.modelData.Id)
            <br>
            <div class="form-group row">
                @Html.LabelFor(model => model.modelData.Name, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.modelData.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.modelData.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.modelData.BrandId, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.modelData.BrandId, new SelectList(Model.brands, "Id", "Name"), "Select", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.modelData.BrandId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.modelData.IsActive, htmlAttributes: new { @class = "control-label col-md-3 m-t-15" })

                <div class="col-md-9">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.modelData.IsActive)
                        @Html.ValidationMessageFor(model => model.modelData.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

            <div class="border-top">
                <div class="card-body" align="center">
                    <button type="Submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        }
    </div>
</div>

MultiAuthDemo/Areas/AdminsArea/Views/Model/Index.cshtml
@model IEnumerable<ASC.Entities.Model>

@{
    ViewBag.Title = "Index";
}
<link href="~/Template/css/Popup-form.css" rel="stylesheet" />

<div class="container-fluid">
    <h1 class="mt-4">Models</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">
            <button id="myBtn" type="Submit" class="btn btn-danger" style="float: right;"><i class="fas fa-plus"></i> Model</button>
        </li>
    </ol>

    <div class="card mb-4">
        <div class="card-header">

            <i class="fas fa-table mr-1"></i>
            DataTable
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.IsActive)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Brand.Name)
                            </th>
                            <th>

                            </th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IsActive)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Brand.Name)
                            </td>
                            <td>
                                <button type="Submit" value="@item.Id" class="Editform btn btn-primary">
                                    <i class="far fa-edit"></i>
                                </button>
                                @if (item.IsActive == true)
                                {
                                    <a href='@Url.Action("Delete","Model", new { id = item.Id })' class="btn btn-danger">
                                        <i class="fas fa-toggle-off"></i>
                                    </a>
                                }
                                else
                                {
                                    <a href='@Url.Action("Delete","Model", new { id = item.Id })' class="btn btn-success">
                                        <i class="fas fa-toggle-on"></i>
                                    </a>
                                }

                            </td>
                        </tr>
                        }
                    </tbody>

                    <tfoot>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.IsActive)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Brand.Name)
                            </th>
                            <th>

                            </th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>


</div>

<div id="myModal" class="modal" style="width:100%; padding-right:30%;">

</div>


@section scripts{
    <script>
        $(document).ready(function () {
            $("#myBtn").click(function (evt) {

                $.get( '@Url.Action("Create", "Model", new {} )', function(data) {
                    $('#myModal').html(data);
                    $('#myModal').css("display", "block");
                });
            });

            $(".Editform").click(function (evt) {
                var CatID = $(this).val();
                $.get('@Url.Action("Edit", "Model")?id=' + CatID, function(data) {
                    $('#myModal').html(data);
                    $('#myModal').css("display","block");
                });
            });
        });
    </script>

    <script type="text/javascript">
        var modal = document.getElementById("myModal");
        window.onclick = function (event) {
            if (event.target == modal) {
                modal.style.display = "none";
                modal.innerHTML = "";
            }
        }
    </script>



    <script>
    $(document).ready(function () {
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "onclick": null,
            "showDuration": "200",
            "hideDuration": "1500",
            "timeOut": "6000",
            "extendedTimeOut": "1200",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        };

        var Type = "@TempData["Type"]";
        var Message = "@TempData["Message"]";
        if (Type == "0") {
            toastr.success(Message, 'The Site Says')
        } else if (Type == "1") {
            toastr.info(Message, 'The Site Says')
        } else if (Type == "2") {
            toastr.warning(Message, 'The Site Says')
        } else if (Type == "3") {
            toastr.error(Message, 'Inconceivable!')
        }
    });
    </script>
}