MultiAuthDemo/Areas/AdminsArea/Controllers/AppointmentController.cs
using ASC.Common;
using ASC.Entities;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace MultiAuthDemo.Areas.AdminsArea.Controllers
{
    public class AppointmentController : Controller
    {
        // GET: AdminsArea/Appointment
        public ActionResult Index()
        {
            return View();
        }

        // GET: AdminsArea/Appointment/Create
        public ActionResult Create(string searchData)
        {
            ServiceBooking serviceBooking = new ServiceBooking();
            CustomerVehicles customerVehicles = null;
            IEnumerable<Dealer> dealers;
            IEnumerable<Service> services;
            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri("https://localhost:44318/");
                //HTTP GET
                var responseTask = client.GetAsync("Dealer/Get");
                var responseTask2 = client.GetAsync("Service/Get");
                responseTask.Wait();
                responseTask2.Wait();
                var result = responseTask.Result;
                var result2 = responseTask2.Result;
                if (result.IsSuccessStatusCode && result2.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IEnumerable<Dealer>>();
                    readTask.Wait();
                    dealers = readTask.Result;

                    var readTask2 = result2.Content.ReadAsAsync<IEnumerable<Service>>();
                    readTask.Wait();
                    services = readTask2.Result;
                }
                else
                {
                    dealers = Enumerable.Empty<Dealer>();
                    services = Enumerable.Empty<Service>();
                    ModelState.AddModelError(string.Empty, "Server error occured while retriving data");
                }
            }
            if (searchData != null)
            {
                using (var client = new HttpClient())
                {

                    client.BaseAddress = new Uri("https://localhost:44318/Customer/");
                    //HTTP GET
                    var responseTask = client.PostAsJsonAsync("GetName/", searchData);
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<CustomerVehicles>();
                        readTask.Wait();
                        customerVehicles = readTask.Result;
                    }
                    else
                    {
                        customerVehicles = null;
                        ModelState.AddModelError(string.Empty, "User is not found with ["+ searchData + "] .Please Try Again !!");
                    }
                }
            }
            AppointmentViewModel appointment = new AppointmentViewModel
            {
                ServiceBooking = serviceBooking,
                CustomerVehicles = customerVehicles,
                Dealers = dealers,
                Services = services
            };
            return PartialView(appointment);
        }


        public ActionResult Edit(int id)
        {

            /*List of Dealer,List Of Services,Appointment by id*/


            ServiceBooking EditBooking = new ServiceBooking();
            CustomerVehicles customerVehicles = null;
            IEnumerable<Dealer> dealers;
            IEnumerable<Service> services;


            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri("https://localhost:44318/");
                //HTTP GET
                var responseTask = client.GetAsync("Dealer/Get");
                var responseTask2 = client.GetAsync("Service/Get");
                var responseTask3 = client.GetAsync("Get /" + id);
                responseTask.Wait();
                responseTask2.Wait();
                responseTask3.Wait();
                var result = responseTask.Result;
                var result2 = responseTask2.Result;
                var result3 = responseTask3.Result;

                if (result.IsSuccessStatusCode && result2.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IEnumerable<Dealer>>();
                    readTask.Wait();
                    dealers = readTask.Result;

                    var readTask2 = result2.Content.ReadAsAsync<IEnumerable<Service>>();
                    readTask.Wait();
                    services = readTask2.Result;

                    var readTask3 = result.Content.ReadAsAsync<ServiceBooking>();
                    readTask.Wait();
                    EditBooking = readTask3.Result;
                }
                else
                {
                    dealers = Enumerable.Empty<Dealer>();
                    services = Enumerable.Empty<Service>();
                    EditBooking = null;
                    customerVehicles = null;
                    ModelState.AddModelError(string.Empty, "Server error occured while retriving data");
                }
            }




            AppointmentViewModel EditAppointment = new AppointmentViewModel
            {
                ServiceBooking = EditBooking,
                Dealers = dealers,
                Services = services,
                CustomerVehicles = customerVehicles,

            };


            return View(EditAppointment);

        }



        [HttpPost]
        public ActionResult Create(ServiceBooking ServiceBooking,int[] servicesIds)
        {      
            try
            {
                ServiceBookingModel serviceBookingModel = new ServiceBookingModel
                {
                    ServiceBooking = ServiceBooking,
                    servicesIds = servicesIds
                };
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:44318/ServiceBooking/");

                    //HTTP POST
                    var postTask = client.PostAsJsonAsync<ServiceBookingModel>("Create", serviceBookingModel);
                    postTask.Wait();

                    var result = postTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        TempData["Type"] = 0;
                        TempData["Message"] = "Model Added successfully";
                        return RedirectToAction("Index");
                    }
                }
                TempData["Type"] = 2;
                TempData["Message"] = "Error Occured While Creating";
                return RedirectToAction("Create");
            }
            catch
            {
                return View();
            }
            

        }

        [HttpPost]
        public ActionResult Edit(ServiceBooking ServiceBooking)
        {
            try
            {
                
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:44318/ServiceBooking/");

                    //HTTP POST
                    var postTask = client.PostAsJsonAsync<ServiceBooking>("Edit", ServiceBooking);
                    postTask.Wait();

                    var result = postTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        TempData["Type"] = 0;
                        TempData["Message"] = "Model Added successfully";
                        return RedirectToAction("Index");
                    }
                }
                TempData["Type"] = 2;
                TempData["Message"] = "Error Occured While Creating";
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }


        }
    }
}

MultiAuthDemo/Areas/AdminsArea/Views/Appointment/Create.cshtml
@model ASC.Common.AppointmentViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/AdminsArea/Views/Shared/_AdminLayoutPage.cshtml";
}
    <div class="container-fluid">
        <h1 class="mt-4">Service Booking</h1>



        <div class="form-horizontal">
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">
                    @*<button id="myBtn" type="Submit" class="btn btn-danger" style="float: right;"><i class="fas fa-plus"></i> Model</button>*@
                    New Booking
                </li>
            </ol>
            @using (Html.BeginForm("Create", "Appointment", FormMethod.Get))
            {
                <div class="form-group">
                    Search Customer:
                    @Html.TextBox("searchData", ViewBag.SearchData as string)
                    <input type="submit" value="Search" class="btn btn-primary" />
                </div>
            }
            <hr />

            @using (Html.BeginForm("Create", "Appointment", FormMethod.Post))
            {

                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                if (Model.CustomerVehicles != null)
                {
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active">
                            Customer Details
                        </li>
                    </ol>

                    <div class="card-body" style="padding-top:0px;padding-bottom:0px;">
                        <div class="table-responsive">
                            <table class="table" width="100%" cellspacing="0">
                                <tr style="border-bottom:1px solid #dee2e6;">
                                    <th>
                                        @Html.DisplayNameFor(model => model.CustomerVehicles.Customer.Name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.CustomerVehicles.Customer.Email)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.CustomerVehicles.Customer.PhoneNumber)
                                    </th>
                                </tr>
                                <tr style="border-bottom:1px solid #dee2e6;">
                                    <td>
                                        @Html.DisplayFor(model => model.CustomerVehicles.Customer.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => model.CustomerVehicles.Customer.Email)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => model.CustomerVehicles.Customer.PhoneNumber)
                                    </td>
                                </tr>
                            </table>
                        </div>

                    </div>

                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active">
                            Vehicles Details
                        </li>
                    </ol>

                    <div class="card-body" style="padding-top:0px;padding-bottom:0px;">
                        <div class="table-responsive">
                            <table class="table" width="100%" cellspacing="0">
                                <tr style="border-bottom:1px solid #dee2e6;">
                                    <th>

                                    </th>
                                    <th>
                                        Name
                                    </th>
                                    <th>
                                        NumberPlate
                                    </th>
                                    <th>
                                        Model
                                    </th>
                                    <th>
                                        Brand
                                    </th>
                                </tr>
                                @foreach (var item in Model.CustomerVehicles.Vehicles)
                                {
                                    <tr style="border-bottom:1px solid #dee2e6;">
                                        <td>
                                            
                                            @Html.RadioButtonFor(m => m.ServiceBooking.VehicleId, item.Id)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.NumberPlate)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Model.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Model.Brand.Name)
                                        </td>
                                    </tr>
                                }


                            </table>
                        </div>

                    </div>
                }


                <ol class="breadcrumb">
                    <li class="breadcrumb-item active">
                        Services Details
                    </li>
                </ol>

                <div class="card-body" style="padding-top:0px;padding-bottom:0px;">
                    <div class="table-responsive">
                        <table class="table" width="100%" cellspacing="0">
                            <tr style="border-bottom:1px solid #dee2e6;">
                                <th>
                                     
                                </th>
                                <th>
                                    Service Name
                                </th>
                                <th>
                                    Service Type
                                </th>
                                <th>
                                    Service Duration
                                </th>
                                <th>
                                    Amount 
                                </th>
                            </tr>
                            @foreach (var item in Model.Services)
                            {
                                <tr style="border-bottom:1px solid #dee2e6;">
                                    <td>
                                        <input type="checkbox" name="servicesIds" value="@item.Id" />
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Type)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Duration)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Amount) <b>&#8377;</b>
                                    </td>
                                </tr>
                            }


                        </table>
                    </div>

                </div>


                <div>

                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active">
                            Other Details
                        </li>
                    </ol>
                    <div class="form-horizontal">

                        <hr />
                        <div class="container">
                            <div class="row">

                                <div class="col-md-6">
                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.ServiceBooking.BookingDate, htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.EditorFor(model => model.ServiceBooking.BookingDate, new { htmlAttributes = new { Type = "Date", @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.ServiceBooking.BookingDate, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.ServiceBooking.PickupAddress, htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.TextAreaFor(model => model.ServiceBooking.PickupAddress, new { @class = "form-control", value = "added text" })
                                            @Html.ValidationMessageFor(model => model.ServiceBooking.PickupAddress, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                </div>
                                <div class="col-md-6">

                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.ServiceBooking.DealerId, htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.DropDownListFor(model => model.ServiceBooking.DealerId, new SelectList(Model.Dealers, "Id", "Name"), "Select", new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.ServiceBooking.DealerId, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        @Html.LabelFor(model => model.ServiceBooking.DropAddress, htmlAttributes: new { @class = "control-label col-md-4" })

                                        <div class="col-md-8">
                                            @Html.TextAreaFor(model => model.ServiceBooking.DropAddress, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.ServiceBooking.DropAddress, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-md-4"></div>
                                        <div class="col-md-6">
                                            <input type="checkbox" id="SameAs" class="checkbox" />
                                            Same as PickUp
                                        </div>

                                    </div>

                                </div>
                            </div>
                        </div>


                        <div align="center" class="form-group" style="border-bottom: 1px solid #eeeeee; margin-bottom: 20px; padding-bottom: 10px;">
                            <div class="col-md-offset-5 col-md-2" align="center">
                                <input type="submit" value="BOOK APPOINTMENT" class="btn btn-info" />

                            </div>
                        </div>
                    </div>

                </div>
            }
        </div>
        </div>

@section scripts{
    <script>     
        $(document).ready(function () {
            $('#SameAs').click(function () {
                if ($(this).is(":checked")) {
                    var Data = $("#ServiceBooking_PickupAddress").val();
                    $('#ServiceBooking_DropAddress').val(Data);
                }
                else {
                     $('#ServiceBooking_DropAddress').val("");
                }
            });
        });
    </script>
}